name: CI
on: push
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Setup project
        uses: npm ci
      - name: Test
        run: npm test -- --no-watch --no-progress
